Custom release title
fregante/release-with-changelog pull request #40
Opened 2021-02-25 09:16 UTC by BelKed

Resolves #27.

- [ ] Add custom title option
- [ ] Update README.md

2021-02-26 18:05 UTC, BelKed commented
@fregante, please, could you review this pull request?

2021-03-08 22:15 UTC, fregante requested changes

2021-03-08 22:15 UTC, fregante commented on index.js
> +		let releaseTitle = core.getInput('title');
```suggestion
		const releaseTitle = core.getInput('title');
```

And then below…

2021-03-08 22:15 UTC, fregante commented on index.js
> +			name: releaseTitle,
```suggestion
			name: releaseTitle.replace('{tag}', pushedTag),
```

2021-03-09 07:02 UTC, BelKed commented on index.js
> +		let releaseTitle = core.getInput('title');
OK

2021-03-09 07:04 UTC, BelKed commented on index.js
> +			name: releaseTitle,
OK

2021-03-09 07:26 UTC, fregante approved these changes

2021-03-09 07:26 UTC, fregante commented on action.yml
> +    description: Custom tile
```suggestion
    description: Custom title for the release
```

2021-03-09 07:27 UTC, merged

2021-03-09 07:29 UTC, fregante commented
I'll wait a few more days before releasing a new version. So if you want to open new PRs you can do so before then

2021-03-25 14:45 UTC, rm3195 commented
Hi @fregante! Any plans for releasing a new version with this change soon?
Thanks!

2021-03-26 15:29 UTC, fregante commented
v3.3.0